apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monte-et-souris
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: monte-et-souris
    # newName/newTag sont réécrits par la pipeline CD :
    #   kustomize edit set image monte-et-souris=<ECR_URI>:<SHA>
    newName: monte-et-souris
    newTag: latest
